// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebbjkjuanuxhqtrhlirc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYmpranVhbnV4aHF0cmhsaXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDE4MzgsImV4cCI6MjA3MjA3NzgzOH0.-wrXoBJFLj5GHNF1FnYb9h0vKJUcab73k5q9LiS4ckk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});